# Generated by Django 5.1.1 on 2024-09-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='active',
            field=models.BooleanField(choices=[(True, 'Online'), (False, 'Offline')]),
        ),
    ]
