# Generated by Django 5.1.1 on 2024-09-25 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0004_offer_created_at_offer_updated_at'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_type', models.CharField(choices=[('sell', 'Buy'), ('buy', 'Sell')], max_length=10)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('canceled', 'Canceled')], max_length=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='offers.offer')),
                ('user_kyc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.userkyc')),
            ],
        ),
    ]
